### ISSUE TITLE
osc library

### ISSUE THREAD

**Issue by avlapp** [gpayer/go-nsm#1]
I saw you did a pull request  'Added server SendTo method #51' for the go-osc library. I'm looking for such functionality as well and looking for the best OSC library for it. I was wondering why you picked the go-osc library for your project and not this library for OSC, which can send from server as well I think: https://github.com/scgolang/osc

**Comment by gpayer** [comment]
scgolang/osc is incredibly old, does not even support modules. My current solution works perfectly for my purposes, so I won't change it.

**Comment by avlapp** [comment]
Thanks for replying. Hm old and not supporting modules (which is quite easy to fix I assume), wouldn't be my most important criteria. I'm more interested in the quality of the library. I can imagine that the fact that it's not actively maintained is a thing.
I didn't expect or asked you to change it, I was just wondering why you picked the go-osc library and nobody seems to use the scgolang/osc library. So far that scgolang/osc library is serving me well, also for this functionality.
